
  - name: Installation and setup of Glance
    apt:
      name: glance
      state: present
      update_cache: yes

  - name: Restart the glance
    service:
      name: glance-api
      state: restarted
      enabled: yes
